version: '3'
services:
  mysql:
    image: mysql:8.0.16
    restart: always
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=123qweASD
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123qweASD
    ports:
      - 3306:3306
  library-app:
    image: gamurar/library
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123qweASD
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/library?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
      - APP_SLEEP=30
    ports:
      - 8080:8080