spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123qweASD
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect