spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/library;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
