spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123qweASD
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect