spring:
  profiles:
    active: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false
  messages:
    basename: i18n/messages