spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/h2/library;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
